apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: managed-care-plan-api-key
  namespace: {{ .Values.appNamespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.clusterSecretStoreName }}
    kind: ClusterSecretStore
  data:
    - secretKey: api_key
      remoteRef:
        key: {{ .Values.awsSecretsManagerSecretApiKeyName }}
        property: apiKey
