apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: connect-cluster
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  build:
    output:
      type: docker
      image: {{ .Values.ecrRepositoryUrl  }}:strimzi-eb-connect-1.1.0
      pushSecret: {{ .Values.ecrSecretName | quote}}
    plugins:
      - name: eventbridge-sink-connector
        artifacts:
          - type: jar
            url: https://github.com/awslabs/eventbridge-kafka-connector/releases/download/v1.0.1/kafka-eventbridge-sink-with-dependencies.jar
  replicas: 1
  bootstrapServers: cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: cluster-cluster-ca-cert
        certificate: ca.crt
  template:
    serviceAccount:
      metadata:
        annotations:
          eks.amazonaws.com/role-arn: {{ .Values.eventBridgeKafkaConnectIamRoleArn | quote }}
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1