apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: amazon-rds-db-secret
  namespace: {{ .Values.appNamespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.clusterSecretStoreName }}
    kind: ClusterSecretStore
  data:
    - secretKey: rds_password
      remoteRef:
        key: {{ .Values.awsSecretsManagerSecretRdsSecretName }}
        property: password
    - secretKey: rds_username
      remoteRef:
        key: {{ .Values.awsSecretsManagerSecretRdsSecretName }}
        property: username